Move to pip-compile-multi (#786)
* Switch from pip-tools to pip-compile-multi

* Switch to pip-compile-multi, splitting out dev deps from prod deps

  It's worked fine, albeit with a TODO in the Dockerfile to actually build a separate dev-specific image,
  which will come in a separate commit.

  Went with the pattern of auto-installing the dependency-management tool via the makefile. Will likely
  switch this to an alert + install instructions

  This change was needed because in-container compilation was failing and various pip+pip-tools versions attempted clashed due to
  ```
  TypeError: make_requirement_preparer() got an unexpected keyword argument 'wheel_download_dir'
  ```
  which may have been a chicken-and-egg problem, but was not worth solving when a simpler route was around.

* Rebuild requirements on the host, not in the container, but retain Makefile commands as the primary
  invocation route - `make compile-requirements` and  `make upgrade-requirements`

* Update makefile-driven UX around compiling and upgrading using pip-compile-multi

Now, instead of force-intalling pip-compile-multi, we get a prompt showing us what do to (and so providing some flexibility)

Also note that some dev subdeps have been minorly bumped.

IMPORTANT: if you currently try to recompile deps results in a failure with long-unmaintained suds-jurko, so this will need swapping out. The current set of deps builds and passes tests, at least

* Drop Salesforce-FuelSDK from imports

No longer needed and was causing a dependency install issue due to its suds-jurko subdep

* Update docs with note about updating requirements

* Add make command for checking for stale dependencies

Invoke with:

   $ make check-requirements

and update hard-pinned dependencies as you wish

* Refactor to run pip-compile-multi within the docker container

This gives us guaranteed install stability regardless of the source platform being used to run the update

Note that pip-tools and pip-compile-multi are installed ONLY for compiling or upgrading requirements, rather than adding them to the main build.
pip-tools needed pinning to a recent version to get around incompatibility issues with pip 21 and pip-tools.

* Update make check-requirements to run in the Docker container

* Typo fix in docs

* Remove make docs from top-level Makefile, because it fails

One can still compile the docs by using the Makefile in /docs and issuing

  $ make clean html

* Update requirements build script

* hard-pin latest working combo of pip, pip-tools and pip-compile-multi
* add in custom header to make recompliation step unambiguous
* update Makefile: remove unneeded upgrade-requirements option; update help
* recompile reqs with minor bumps

* Remove mention of upgrade-requirements from codebase - redundant