Switch from pip-tools to pip-compile-multi
* Switch to pip-compile-multi, splitting out dev deps from prod deps

  It's worked fine, albeit with a TODO in the Dockerfile to actually build a separate dev-specific image,
  which will come in a separate commit.

  Went with the pattern of auto-installing the dependency-management tool via the makefile. Will likely
  switch this to an alert + install instructions

  This change was needed because in-container compilation was failing and various pip+pip-tools versions attempted clashed due to
  ```
  TypeError: make_requirement_preparer() got an unexpected keyword argument 'wheel_download_dir'
  ```
  which may have been a chicken-and-egg problem, but was not worth solving when a simpler route was around.

* Rebuild requirements on the host, not in the container, but retain Makefile commands as the primary
  invocation route - `make compile-requirements` and  `make upgrade-requirements`